services:
  mysql:
    image: mysql:8.4.2
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_USER: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - ./mysql/var/lib/mysql:/var/lib/mysql
    ports:
      - 127.0.0.1:${MYSQL_PORT}:3306
    networks:
      - ultron
    restart: always

  redis:
    image: redis:7.2.1
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis/conf:/usr/local/etc/redis/redis.conf
    ports:
      - 127.0.0.1:${REDIS_PORT}:6379
    networks:
      - ultron
    restart: always

  cerbos:
    image: ghcr.io/cerbos/cerbos:0.37.0
    command: server --config=/config/conf.yaml
    volumes:
      - ./cerbos/conf.yaml:/config/conf.yaml
      - ./cerbos/policies:/config/policies
    ports:
      - 127.0.0.1:${CERBOS_HTTP_PORT}:3592
      - 127.0.0.1:${CERBOS_GRPC_PORT}:3593
    networks:
      - ultron
    restart: always

networks:
  ultron:
